name: Feature Request
description: Suggest an idea or enhancement for the Fastlane plugin
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving this Fastlane plugin!
        Please provide context so we can understand your feature request.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What feature would you like to see added?
      placeholder: "Describe the new behavior or improvement"
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
      description: Explain the problem this feature solves or why it's useful.
      placeholder: "Why do you need this?"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed implementation
      description: If you have an idea for how this could be implemented, describe it here.
      placeholder: "Optional: how you would implement it"
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example Fastlane usage (optional)
      description: Show how the feature might look when used in a Fastlane lane.
      render: ruby
      placeholder: |
        dsym_upload(
          new_option: true
        )
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any context or screenshots related to the feature request.
    validations:
      required: false
